### ISSUE TITLE
Use shex or shacl to define shapes for various feature graphs

### ISSUE THREAD

**Issue by cmungall** [OBF/FALDO#30]
Exchange format like GFF and databases like Chado allows for arbitrary configurations of feature graphs. The GFF spec provides recommendations, e.g. so called 3-level graphs (gene->transcript->exon) but this is encoded in free text to be implemented procedurally by validators.

One of the original ideas was to use SO to constrain the shapes of these graphs but of course OWL is open world, and SO is under-axiomatized so in practice SO just serves to document like associations.

It seems that faldo plus a shape language would be ideal here, and very useful for faldo in general

**Comment by JervenBolleman** [comment]
Yes, it would be nice. We should investigate this. I won't have time before Biohackathon2017 to work on it, but do have a preference for ShACL but would like to see both.

**Comment by cmungall** [comment]
closing this in favor of the more generic #40
