### ISSUE TITLE
Move this repo to an org

### ISSUE THREAD

**Issue by cmungall** [OBF/FALDO#31]
Not to diminish the excellent work @JervenBolleman has done but I think an org rather than user space would be more befitting a standard we want to see adopted widely. There are many to choose from, or we could create one for this purpose.

**Comment by JervenBolleman** [comment]
I would be happy to move it to some where appropriate. Do you have a suggestion?

**Comment by peterjc** [comment]
We could asked the Open Bioinformatics Foundation http://www.open-bio.org which has an organisation account on GitHub, @OBF

Disclaimer: I am a member of their board and current treasurer, and would support this if the FALDO community thought it was a good idea.

**Comment by cmungall** [comment]
Is there is a biohackathon org?

GMOD is another option, a lot of producers and consumers of faldo should 
be GMOD tools and databases (GFF3 is used now)

We could simply have a new org 'FALDO'

**Comment by peterjc** [comment]
We could create a FALDO organisation account, but the long term viability of that worries me slightly (which one of the reasons against leaving this under a single person's account).

I don't think there is a BioHackathon GitHub account, they've used DBCLS' for things like https://github.com/dbcls/bh16

GMOD would be another good idea.

**Comment by cmungall** [comment]
I didn't see @peterjc's suggestion earlier. I favor it.

**Comment by JervenBolleman** [comment]
@peterjc I am OK with OBF. I will write @OBF per e-mail if they will accept the contribution and will ask the faldo group if anyone objects.

**Comment by JervenBolleman** [comment]
I asked on the [FALDO group](https://groups.google.com/d/msg/faldo/A2RYDVWksaY/06KYju-1BgAJ)

**Comment by peterjc** [comment]
Note our board at open-bio.org address gets manually moderated due to spam, so I suggest you CC my GoogleMail address which will remind me to check the incoming mail reaches the full board.

**Comment by micheldumontier** [comment]
Another option might be the HCLS github org - https://github.com/W3C-HCLSIG
we also have the hcls dataset description work there.

**Comment by JervenBolleman** [comment]
@OBF accepted to offer and is willing to accept the FALDO repository. If no objections received we will transfer this repository at 2017/09/11 at 19:30 in Morioka at the 2017 biohackathon.

**Comment by JervenBolleman** [comment]
We are now inside the @OBF/faldo team!
